build_script:
- C:\msys64\usr\bin\bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
- C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Sy"
- C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S gcc git make"
test_script:
- C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER && make -k check V=3"
- C:\msys64\usr\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER && make -k check LEGACY=1 V=3"
